### ISSUE TITLE
Report error after installing

### ISSUE THREAD

**Issue by huyingjie** [meteor/hexo-theme-meteor#49]
I run `hexo s`. The websit is running but Terminal reports `Error: Cannot find module './build/Release/DTraceProviderBindings'` error.

![screen shot 2018-01-26 at 2 59 06 am](https://user-images.githubusercontent.com/4664280/35430135-f3792d44-0244-11e8-96c2-5e5028fed6ec.png)

**Comment by abernix** [comment]
This appears to be a problem with a mismatched Node ABI ([`NODE_MODULE_VERSION`](https://nodejs.org/en/download/releases/))

What version of `node` are you using to run it?  If you've changed versions of `node` since you originally installed your `node_modules`, please try running `npm rebuild` or, alternatively, running `rm -rf node_modules` and running `npm install` again.  See if that resolves your problem.

**Comment by huyingjie** [comment]
@abernix The node version is v8.5.0.

I updated nodejs using 
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```
Then I rann `node -v`. It showed v8.5.0.
I installed v8.9.4 from https://nodejs.org/en/, it still showed v8.5.0.

It is werid.

**Comment by huyingjie** [comment]
I tried `npm install hexo --no-optional` from https://github.com/hexojs/hexo/issues/1922. It works.
Now it showed `(node:4555) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.`. It is not theme's problem. I am searching online for the solution. Thank you.
