### ISSUE TITLE
Clicking on anchors adds backslashes before periods

### ISSUE THREAD

**Issue by glasser** [meteor/hexo-theme-meteor#57]
- Go to https://www.apollographql.com/docs/engine/proxy-release-notes.html
- Click on the link icon to the left of the v1.0.4 header
- It properly smooth scrolls to the top
- Look at the URL bar
- See https://www.apollographql.com/docs/engine/proxy-release-notes.html#v1\.0\.4

Where did the backslashes come from? They break links. Note that "copy link address" on the link gets the right error without backslash.

@abernix this might be up your alley?

**Comment by abernix** [comment]
Yes, I've seen this and I presume it's something in our scripts doing it (probably the thing that highlights the sidebar or auto-expands the sub-headings when you're within that section?) but haven't looked into what it is yet.

**Comment by abernix** [comment]
This hadn't been a more prominent problem until `proxy-release-notes.md` since markdown header-syntax (e.g. `#`, `##`, `###`) normally replaces symbols (something along the lines of `[\W]`, I believe) with hyphens (`-`) when it generates the `id`s for the resulting `<h#>` tags.

In the case of `proxy-release-notes.md` (and other newer docs markdown), we manually generate the anchor to prevent it from breaking permalinks if we change the header itself, and the proxy versions are some of the only headers which utilize periods (à la, `1.0.4`) causing this `smooth-scroll` bug to rear its head.

Anyhow, fixed with an upgrade of `smooth-scroll` (which is now served via CDN too).  https://github.com/meteor/hexo-theme-meteor/commit/248d0bad7b15ac973251aeedde280677247515b2.

Thanks for reporting this!

**Comment by glasser** [comment]
Yeah, I didn't think it was helpful to include dates in the anchors along with the version number. Thanks!

**Comment by abernix** [comment]
@glasser This is deployed now to the Engine docs! (i.e. fixed).

**Comment by glasser** [comment]
Thanks!
